version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - terraform --version
      - terraform init -input=false
      - terraform validate
      #- terraform destroy -input=false
      #- terraform plan -lock=false -input=false
      - terraform $TF_COMMAND -auto-approve
  post_build:
    commands:
      - echo terraform $TF_COMMAND complete on 'date'
